### PR TITLE
Feature/update dalpy to string 22

### LINKED ISSUE #22: Update dalpy_to_string to display object type
**Is your feature request related to a problem? Please describe.**
The current iteration of the `dalpy_to_string` function does not indicate the object type in the string representation of DALPy objects. This can be confusing when the `dalpy_to_string` representation and other base python object representations coincide, for example with DALPy `Array` and Python `list`.

**Describe the solution you'd like**
Some indication of the object type should be added to the `dalpy_to_string` function's string representation generation for each DALPy provided data structure. For example:
```
Array[1,2,3]
Queue[1,2,3]
```

**Additional context**
Here is a screenshot from a Brandeis University Spring 2022 COSI21a student's submission for which they were confused as to why they were failing test cases, despite the output and expected appearing identical. 
Screen Shot 2022-03-22 at 12 41 28 PM
[README.md](https://github.com/DALPy-Developers/DALPy/files/8329466/README.md)

### PR DESCRIPTION
**Pull request by wwxiao09**
I updated dalpy_to_string to specify the object name for the following dalpy data structures:

1. Array
2. Array2D
3. Queue
4. Stack
5. Set
6. BinaryTreeNode
7. NaryTreeNode

, and added corresponding tests to test_utils_tests.

Please review my request.

### CODE REVIEW

**Review by ChamiLamelas — APPROVED** [review]

**Review by ChamiLamelas — CHANGES_REQUESTED** [review]
`dalpy_to_string` should be documented to clarify that `"BinaryTree"`, `"NaryTree"` are prepended to the beginning of string outputs for `BinaryTreeNode` and `NaryTreeNode`. Users could be confused and think `BinaryTree` and `NaryTree` are data structures.

**Comment by wwxiao09** [comment]
I've clarified that in the documentation of dalpy_to_string.

**Review by EitanJoseph — APPROVED** [review]
Looks good.

**Review by ChamiLamelas — CHANGES_REQUESTED** [review]
As noted in my previous review, I think something like this could be better: 

```
Calling dalpy_to_string on `dalpy.trees.BinaryTreeNode` or `dalpy.trees.NaryTreeNode` displays the entire tree rooted at that node prepended with `"BinaryTree"` and `"NaryTree"` respectively. This is done to clarify the nodes themselves are not holding the data listed after it.
```

**Review by ChamiLamelas — APPROVED** [review]

**Pull request merged**
